version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      # --- Configurações Gerais ---
      - TZ=America/Sao_Paulo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_DISABLE_PRODUCTION_WEBHOOK_AUTHENTICATION=true
      
      # --- Credenciais Lidas do Arquivo .env ---
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}    
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}  
      - WEBHOOK_URL=${WEBHOOK_URL}        
      
    volumes:
      - ./n8n_data:/home/node/.n8n

  redis:
    image: redis:latest
    platform: linux/amd64
    restart: always
    # --- Senha Lida do Arquivo .env ---
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: